# Generated by Django 2.2.28 on 2022-08-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('message', models.TextField(default='', max_length=300)),
                ('price_of_apple', models.FloatField(default=2.5)),
                ('number_of_apples', models.PositiveIntegerField(default=0)),
                ('amount', models.FloatField(default=0.0)),
                ('charge', models.FloatField(default=0.0)),
                ('amount_received', models.FloatField(default=0.0)),
            ],
        ),
    ]
